defmodule Auth.Repo.Migrations.AddRefreshTokensUserFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:refresh_tokens) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "refresh_tokens_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:refresh_tokens, [:user_id])
  end

  def down do
    drop_if_exists index(:refresh_tokens, [:user_id])

    drop constraint(:refresh_tokens, "refresh_tokens_user_id_fkey")

    alter table(:refresh_tokens) do
      modify :user_id, :uuid
    end
  end
end
