defmodule Auth.Repo.Migrations.AddLoginRegisterFieldsAndRefreshTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :username, :citext, null: false
      add :birthday, :date, null: false
      add :promo_code, :text
      add :tos_agreed_at, :utc_datetime, null: false
      add :tos_version, :text, null: false
    end

    create unique_index(:users, [:username], name: "users_unique_username_index")

    create table(:refresh_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false
      add :token_hash, :text, null: false
      add :last_used_at, :utc_datetime, null: false
      add :revoked_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:refresh_tokens, [:token_hash],
             name: "refresh_tokens_unique_token_hash_index"
           )
  end

  def down do
    drop_if_exists unique_index(:refresh_tokens, [:token_hash],
                     name: "refresh_tokens_unique_token_hash_index"
                   )

    drop table(:refresh_tokens)

    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    alter table(:users) do
      remove :tos_version
      remove :tos_agreed_at
      remove :promo_code
      remove :birthday
      remove :username
    end
  end
end
