defmodule Auth.Repo.Migrations.AddRefreshTokenFamilyId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:refresh_tokens) do
      add :family_id, :uuid
    end

    execute "UPDATE refresh_tokens SET family_id = gen_random_uuid() WHERE family_id IS NULL"

    alter table(:refresh_tokens) do
      modify :family_id, :uuid, null: false
    end

    create index(:refresh_tokens, [:family_id])
  end

  def down do
    drop_if_exists index(:refresh_tokens, [:family_id])

    alter table(:refresh_tokens) do
      remove :family_id
    end
  end
end
